### ISSUE TITLE
Read sensor data example needed 

### ISSUE THREAD

**Issue by tilentur** [Mr-Markus/ZigbeeNet#116]
Could you please prepare an example showing how to connect and read data from a sensor. For example xiaomi Aqara Temperature and Humidity (WSDCGQ11LM) sensor

**Comment by Mr-Markus** [comment]
Just See here https://github.com/Mr-Markus/ZigbeeNet/tree/develop/samples/ZigBeeNet.PlayGround

And also Wiki Page

**Comment by Mr-Markus** [comment]
Feel free to open another issue for further questions
