### ISSUE TITLE
Duplicate ZCL cluster attribute

### ISSUE THREAD

**Issue by thombrink** [Mr-Markus/ZigbeeNet#121]
On the master branch ZclMeteringCluster.cs contains a duplicate attribute value.

The values below both have the value '0x0430' and therefore the dictionary will throw an exception.
ATTR_PREVIOUSDAY16CONSUMPTIONDELIVERED
ATTR_CURRENTWEEKCONSUMPTIONDELIVERED 

The bug is already solved in de dev branch by this commit:
https://github.com/Mr-Markus/ZigbeeNet/commit/93758f1fcce96f4b09f0ff760cbf48439b4b16aa

Could you merge this commit to master and publish a new nuget?

**Comment by Mr-Markus** [comment]
Done
