### ISSUE TITLE
Can't discover any endpoints using ConBee II

### ISSUE THREAD

**Issue by reinux** [Mr-Markus/ZigbeeNet#123]
I'm not able to discover any endpoints using ConBee II, either in my own code or using the playground.

Tried with a Tradfri light, a Tradfri remote and a Sinope dimmer.

Thought this might be related to https://github.com/Mr-Markus/ZigbeeNet/issues/117, but commenting the `await RequestNetworkAddress()` and returning either false or true instead doesn't work for me.

I have no trouble getting it to work with deCONZ/Phoscon, so I think the hardware should be fine.

Thanks for any help!

**Comment by Mr-Markus** [comment]
@DavidKarlas can you help?

**Comment by jgmdavies** [comment]
@reinux  I get the same with my ConBee II - always a problem with discovery using ZigbeeNet, but the h/w is fine with deCONZ/Phoscon.  I'll go back to it in a day or two and try again.
Jim

**Comment by DavidKarlas** [comment]
Sorry for slow response everyone... I opened this PR as workaround problem with NetworkAddressRequest... https://github.com/Mr-Markus/ZigbeeNet/pull/124

I'm not sure how it ever worked for me, I think I didn't use Discoverer and Playground at time I was writing driver... And didn't use it since...

**Comment by reinux** [comment]
Ooh, that works! Thanks!

**Comment by Mr-Markus** [comment]
I merged PR #124 into develop. I would also create a new nuget package version for this today

**Comment by reinux** [comment]
Closing because it's resolved. Thanks @DavidKarlas and @Mr-Markus !
