### ISSUE TITLE
Usage of C# Zigbee Library and support

### ISSUE THREAD

**Issue by sorinpenteleiciuc** [Mr-Markus/ZigbeeNet#132]
Hello,

   I contact you on behalf of P3-Group (   Our office is in Düsseldorf)  and would like to ask you some questions regarding the Zigbee Library. https://github.com/Mr-Markus/ZigbeeNet . Because we would like to use it. We are also in contact with Chris Jackson from ZSmartSytems. Could you please send me a reply mail to : Sorin.Penteleiciuc@p3-group.com
@DavidKarlas  @Mr-Markus  @DavidKarlas  @nicolaiw  @spudwebb 

Thank you and best regards,
Sorin

**Comment by Mr-Markus** [comment]
Hi @sorinpenteleiciuc,

thanks for your interest in this project. I am the founder of this repository and would support you to get it working with your project.
I started the project with Texas Instrument CC253x hardware and other implementations were followed by other contributors. I would send you an e-mail to get in contact with you.

Grüße aus Deutschland
Markus
