### ISSUE TITLE
Groups Cluster

### ISSUE THREAD

**Issue by kristred** [Mr-Markus/ZigbeeNet#137]
Hello,

I have been using this library for a Zigbee project and it is really helpful.

I noticed a small bug with GetGroupMembershipCommandResponse response.

When I send GetGroupMembershipCommand command to a device that is in one group or more, I get the response, where GroupCount is correct and somehow GroupList is empty. I think the bits are read incorrectly.

**Comment by Mr-Markus** [comment]
I have published a new version 1.4.0 of ZigBeeNet that should contain a fix for your problem
