### ISSUE TITLE
Digi XBee 3 USB support

### ISSUE THREAD

**Issue by oising** [Mr-Markus/ZigbeeNet#138]
I just bought a Digi Xbee 3 USB key and unfortunately it doesn't seem to work:

![image](https://user-images.githubusercontent.com/1844001/104376292-ce9ac380-54f2-11eb-989d-6e6dc7a6ef01.png)

@andreasfedermann  -- I see you wrote the initial implementation. Is there anyway that I could help in order to fix this? Thank you!

**Comment by spudwebb** [comment]
are you sure the 115200 baud rate is correct (you can pass it as a command line parameter) ?
I have a Digi XStick that works with the Playground app with a baud rate set to 9600

**Comment by oising** [comment]
works from 1200bps to 961kbps according to https://media.digikey.com/pdf/Data%20Sheets/Digi%20International%20PDFs/Digi_XBee_3_USB_Adapter_7-17-19.pdf

**Comment by oising** [comment]
tried with 9600 8n1

![image](https://user-images.githubusercontent.com/1844001/104381467-79fb4680-54fa-11eb-9cd0-66d925dbc555.png)

**Comment by oising** [comment]
Flashed to latest zigbee 3 stack (which is emberznet 6.7.x) -- everything is fine in XCTU tool

![image](https://user-images.githubusercontent.com/1844001/104381563-aadb7b80-54fa-11eb-8872-1821148e2d91.png)

**Comment by oising** [comment]
So, I am reading the specifics of the AT command set for Xbee and I see that it's **not** in Command mode by default (it's in "Transparent" mode) -- you have to issue `+++` on the line and wait 1 second for the OK to return before sending AT commands - such as a software reset FR (the point at where it's failing right now) -- I can't see anywhere offhand where you might be sending the `+++` sequence -- is it possible that the Xbee model this was tested on is in Command mode by default?

**Comment by oising** [comment]
Ah, so switching the XBee3 into API mode (default is Transparent mode) allowed the playground to initialize... I also had the chip in coordinator mode and not router but I'm not sure if that is an issue. API mode works. I set the mode using XCTU tool.
