### ISSUE TITLE
Threadsafty

### ISSUE THREAD

**Issue by nicolaiw** [Mr-Markus/ZigbeeNet#2]
Use Threadsafe enumeration for the queue

https://github.com/Mr-Markus/ZigbeeNet/blob/12d61ee1416e4cf8d8b7e06aa8aaef7ea7e8475f/src/ZigbeeNet.CCZnp/CCZnp.cs#L28

**Comment by Mr-Markus** [comment]
Threadsafe ConcurrentQueue used. Thanks!
