### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by eiaro** [Mr-Markus/ZigbeeNet#4]
> ZpiObject.cs(120,26): error CS0246: The type or namespace name 'DEBUG' could not be found (are you missing a using directive or an assembly reference?) [/home/pi/src/ZigbeeNet/src/ZigbeeNet.CCZnp/ZigbeeNet.CC.csproj]

> ZpiSREQ.cs(80,24): error CS0246: The type or namespace name 'DEBUG' could not be found (are you missing a using directive or an assembly reference?) [/home/pi/src/ZigbeeNet/src/ZigbeeNet.CCZnp/ZigbeeNet.CC.csproj]

**Comment by Mr-Markus** [comment]
Fixed with commit e31f5e4926f7594f6ead555327523d58dd2ca352

Initial git clone and rebuild succeded
