### ISSUE TITLE
Consider removing the call to .Result and use async/await all the way.

### ISSUE THREAD

**Issue by nicolaiw** [Mr-Markus/ZigbeeNet#40]
https://github.com/Mr-Markus/ZigbeeNet/blob/develop/libraries/ZigBeeNet/ZCL/ZclCluster.cs#L352

https://github.com/Mr-Markus/ZigbeeNet/blob/develop/libraries/ZigbeeNet.Hardware.ConBee/ZigbeeDongleConBee.cs#L58

We should avoid to call Task.Result. Instead we should use async/await.

**Comment by Mr-Markus** [comment]
I can't find any Task.Result calls anymore. So this issue can be closed in my opinion

**Comment by nicolaiw** [comment]
Hello Markus,

would you mind to reopen this issue as a reminder ? Maybe I will find the time to have a look at this.

Regards,
Nicolai

**Comment by nicolaiw** [comment]
https://stackoverflow.com/questions/47284290/when-is-the-best-place-to-use-task-result-instead-of-awaiting-task
