### ISSUE TITLE
Use more badges to show our high code quality standard

### ISSUE THREAD

**Issue by andreasfedermann** [Mr-Markus/ZigbeeNet#62]
To get an overview of existing badges take a look at https://github.com/dwyl/repo-badges. I don’t know if they are all available for a C# project but I‘ll check it out if you want. 
I think it would be a good possibility to present the quality of the code. 
But we have to discuss which badges we want to use first.

Regards.

**Comment by nicolaiw** [comment]
https://github.com/dwyl/repo-badges#github-repo-hit-counter- would be interesting :D

And of course Code Coverage :)

Best regards.
