### ISSUE TITLE
[WIP] ConBee II support?

### ISSUE THREAD

**Issue by jgmdavies** [Mr-Markus/ZigbeeNet#63]
Hi All,

Does the current XBee support work for a ConBee II dongle please?

Thanks,
Jim

**Comment by Mr-Markus** [comment]
Hi @jgmdavies,
we have no Conbee support at the moment. But our library is open for it if somebody will implement it.

As far as I know XBee is from Digi and Conbee from Dresden Elektronik, so there are two implementations which are different. Do you have heard about a relation between these two manufacturers?

**Comment by jgmdavies** [comment]
Thanks Markus.

You're right of course, and no, I don't know of a relationship - I'm afraid I was being over-optimistic!

**Comment by DavidKarlas** [comment]
@jgmdavies FYI, there is PR now open that adds support for ConBee https://github.com/Mr-Markus/ZigbeeNet/pull/94

**Comment by Mr-Markus** [comment]
Great!

**Comment by jacobussystems** [comment]
Fantastic - many thanks for alerting me to this David!
Jim

**Comment by Mr-Markus** [comment]
@DavidKarlas 
Are you still working on this?

**Comment by DavidKarlas** [comment]
No, but its working as is. I'm not aware of any bug, so I guess this can be closed.

**Comment by Mr-Markus** [comment]
Great. I didn't dive deep in this issue yet, but do you think it should be possible to control other devices, too?
In my opinion it should not matter if you control light or other devices if the ZigBee ZCL packet is correctly sending and receiving over serial port.

**Comment by DavidKarlas** [comment]
I don't see why, other devices wouldn't work. As you said, since ZigBee ZCL packet are flowing correctly... Everything should just work...

**Comment by Mr-Markus** [comment]
Well done. This was a great improvment and PR from you. Many thanks. I am very happy about this and our third hardware implementation 😊
