### ISSUE TITLE
Issue comparing Nodes in ZigBeeNode.UpdateNode()

### ISSUE THREAD

**Issue by spudwebb** [Mr-Markus/ZigbeeNet#85]
The comparison of AssociatedDevices, BindingTable, Neighbors and Routes in UpdateNode() always return false because we use the default Object.Equals method which just compares the references.

We should compare the actual content of the list with something like this:
http://msdn.microsoft.com/en-us/library/bb348567%28v=vs.110%29.aspx
 
Also why are they List whereas in the java project they are HashSet

**Comment by spudwebb** [comment]
in the pull request #87, I changed the List to HashSet and compared them suing SetEquals() method.

**Comment by Mr-Markus** [comment]
Thx. I merged the PR
