### ISSUE TITLE
Abstract Hardware Interface

### ISSUE THREAD

**Issue by nicolaiw** [Mr-Markus/ZigbeeNet#9]
A end user should probably only need to do:
```
var zigbeeInt = ZigbeeNet.CC2531(); // Static function to initialize the interface
zigbeeInt.PacketReceived += MyPacketHandler;
zigbeeint.Send(amazing stuff);
```

_Originally posted by @eiaro in https://github.com/Mr-Markus/ZigbeeNet/issues/6#issuecomment-430584007_

**Comment by nicolaiw** [comment]
I currently do not have any Hardware for testing but already ordered one. May be we could have a look at https://github.com/zsmartsystems/com.zsmartsystems.zigbee (java). This project also includes code for hardware abstraction. One of the supportet hardware is the cc2531 (https://github.com/zsmartsystems/com.zsmartsystems.zigbee/tree/master/com.zsmartsystems.zigbee.dongle.cc2531). It looks well structured and may be we can take over some of the Ideas.

**Comment by Mr-Markus** [comment]
done!
